/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package addressbook;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;

/**
 *
 * @author Ishanka
 */
public class AddressBookViewForm1 extends javax.swing.JFrame {

    /**
     * Creates new form AddressBookViewForm1
     */
    public AddressBookViewForm1() {
        initComponents();

       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        addressTxt = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        contactTxt = new javax.swing.JTextField();
        emailTxt = new javax.swing.JTextField();
        searchTxt = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        lnameTxt = new javax.swing.JTextField();
        btnUpdate = new javax.swing.JButton();
        btnView = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();
        fnameTxt = new javax.swing.JTextField();
        btnAdd = new javax.swing.JButton();
        btnSearch = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Haettenschweiler", 1, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 255));
        jLabel1.setText(" Address Book");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(308, 12, 255, -1));

        jLabel2.setFont(new java.awt.Font("Rockwell Extra Bold", 0, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 0, 51));
        jLabel2.setText("Email");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 190, 170, 30));

        jLabel3.setFont(new java.awt.Font("Rockwell Extra Bold", 0, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 0, 51));
        jLabel3.setText("Last Name");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 90, 170, 30));

        jLabel4.setFont(new java.awt.Font("Rockwell Extra Bold", 0, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 0, 51));
        jLabel4.setText("Address");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 140, 170, 30));

        addressTxt.setBackground(new java.awt.Color(255, 255, 255));
        addressTxt.setFont(new java.awt.Font("Goudy Stout", 1, 18)); // NOI18N
        addressTxt.setForeground(new java.awt.Color(0, 0, 0));
        jPanel1.add(addressTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 140, 750, 40));

        jLabel5.setFont(new java.awt.Font("Rockwell Extra Bold", 0, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 0, 51));
        jLabel5.setText("First Name");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 90, 170, 30));

        contactTxt.setBackground(new java.awt.Color(255, 255, 255));
        contactTxt.setFont(new java.awt.Font("Goudy Stout", 1, 18)); // NOI18N
        contactTxt.setForeground(new java.awt.Color(0, 0, 0));
        jPanel1.add(contactTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 190, 280, 40));

        emailTxt.setBackground(new java.awt.Color(255, 255, 255));
        emailTxt.setFont(new java.awt.Font("Goudy Stout", 1, 18)); // NOI18N
        emailTxt.setForeground(new java.awt.Color(0, 0, 0));
        jPanel1.add(emailTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 190, 280, 40));

        searchTxt.setBackground(new java.awt.Color(255, 255, 255));
        searchTxt.setFont(new java.awt.Font("Goudy Stout", 1, 18)); // NOI18N
        searchTxt.setForeground(new java.awt.Color(0, 0, 0));
        jPanel1.add(searchTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 370, 280, 40));

        jLabel6.setFont(new java.awt.Font("Rockwell Extra Bold", 0, 24)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 0, 51));
        jLabel6.setText("Contact");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 190, 170, 30));

        lnameTxt.setBackground(new java.awt.Color(255, 255, 255));
        lnameTxt.setFont(new java.awt.Font("Goudy Stout", 1, 18)); // NOI18N
        lnameTxt.setForeground(new java.awt.Color(0, 0, 0));
        jPanel1.add(lnameTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 90, 280, 40));

        btnUpdate.setFont(new java.awt.Font("Goudy Stout", 1, 18)); // NOI18N
        btnUpdate.setForeground(new java.awt.Color(0, 0, 255));
        btnUpdate.setText("Update");
        btnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateActionPerformed(evt);
            }
        });
        jPanel1.add(btnUpdate, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 300, 286, 44));

        btnView.setFont(new java.awt.Font("Goudy Stout", 1, 18)); // NOI18N
        btnView.setForeground(new java.awt.Color(0, 0, 255));
        btnView.setText("View ");
        btnView.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewActionPerformed(evt);
            }
        });
        jPanel1.add(btnView, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 370, 286, 44));

        btnDelete.setFont(new java.awt.Font("Goudy Stout", 1, 18)); // NOI18N
        btnDelete.setForeground(new java.awt.Color(0, 0, 255));
        btnDelete.setText("Delete");
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });
        jPanel1.add(btnDelete, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 300, 286, 44));

        fnameTxt.setBackground(new java.awt.Color(255, 255, 255));
        fnameTxt.setFont(new java.awt.Font("Goudy Stout", 1, 18)); // NOI18N
        fnameTxt.setForeground(new java.awt.Color(0, 0, 0));
        jPanel1.add(fnameTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 90, 280, 40));

        btnAdd.setFont(new java.awt.Font("Goudy Stout", 1, 18)); // NOI18N
        btnAdd.setForeground(new java.awt.Color(0, 0, 255));
        btnAdd.setText("Add ");
        btnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddActionPerformed(evt);
            }
        });
        jPanel1.add(btnAdd, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 300, 286, 44));

        btnSearch.setFont(new java.awt.Font("Goudy Stout", 1, 18)); // NOI18N
        btnSearch.setForeground(new java.awt.Color(0, 0, 255));
        btnSearch.setText("Search");
        btnSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchActionPerformed(evt);
            }
        });
        jPanel1.add(btnSearch, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 370, 286, 44));
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 460, 970, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 986, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 446, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
        // TODO add your handling code here:
        String fname = fnameTxt.getText();
        String lname = lnameTxt.getText();
        String address = addressTxt.getText();
        String contact = contactTxt.getText();
        String email = emailTxt.getText();
        
        String SQL = "insert into myaddress values (?,?,?,?,?)";
        
        try {
            Class.forName("com.mysql.jdbc.Driver");
        } catch (ClassNotFoundException ex) {
           JOptionPane.showMessageDialog(this,"Driver Not Found");
        }
      
        try {
            Connection conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/addressbook", "root", "7278");
            PreparedStatement st = conn.prepareStatement(SQL);
            st.setObject(1, fname);
            st.setObject(2, lname);
            st.setObject(3, address);
            st.setObject(4, contact);  
            st.setObject(5, email);
            int res = st.executeUpdate();
            if (res>0) {
                 JOptionPane.showMessageDialog(this,"Contact Added !");
                 fnameTxt.setText(null);
                 lnameTxt.setText(null);
                 addressTxt.setText(null);
                 contactTxt.setText(null);
                 emailTxt.setText(null);
            }else{
                 JOptionPane.showMessageDialog(this,"Try Again !");
            } 
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(this, ex.getMessage());
        }
        
    }//GEN-LAST:event_btnAddActionPerformed

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        // TODO add your handling code here:
        String SQL = "delete from myaddress where firstname = ? and lastname = ?";
        
        String fname = fnameTxt.getText();
        String lname = lnameTxt.getText();
        try {
            Class.forName("com.mysql.jdbc.Driver");
        } catch (ClassNotFoundException ex) {
           JOptionPane.showMessageDialog(this,"Driver Not Found");
        }
      
          try {
            Connection conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/addressbook", "root", "7278");
            PreparedStatement st = conn.prepareStatement(SQL);
            st.setObject(1, fname);
            st.setObject(2, lname);
            
            int res = st.executeUpdate();
            if (res>0) {
                 JOptionPane.showMessageDialog(this,"Contact Deleted !");
                 fnameTxt.setText(null);
                 lnameTxt.setText(null);
                 addressTxt.setText(null);
                 contactTxt.setText(null);
                 emailTxt.setText(null);
                 searchTxt.setText(null);
            }else{
                 JOptionPane.showMessageDialog(this,"Try Again !");
            } 
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(this, ex.getMessage());
        }
    }//GEN-LAST:event_btnDeleteActionPerformed

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
        // TODO add your handling code here:
        String SQL = "update myaddress set address = ? , contact = ? , email = ? where firstname = ? and lastname = ? ";
        
        String fname = fnameTxt.getText();
        String lname = lnameTxt.getText();
        try {
            Class.forName("com.mysql.jdbc.Driver");
        } catch (ClassNotFoundException ex) {
           JOptionPane.showMessageDialog(this,"Driver Not Found");
        }
         try {
            Connection conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/addressbook", "root", "7278");
            PreparedStatement st = conn.prepareStatement(SQL);
            st.setObject(4, fname);
            st.setObject(5, lname);
            st.setObject(1,addressTxt.getText());
            st.setObject(2,contactTxt.getText());
            st.setObject(3,emailTxt.getText());
            
            int res = st.executeUpdate();
            if (res>0) {
                
                 fnameTxt.setText(null);
                 lnameTxt.setText(null);
                 addressTxt.setText(null);
                 contactTxt.setText(null);
                 emailTxt.setText(null);
                 searchTxt.setText(null);
                 JOptionPane.showMessageDialog(this,"Contact Updated !");
                 
            }else{
                 JOptionPane.showMessageDialog(this,"Try Again !");
            } 
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(this, ex.getMessage());
        }
    }//GEN-LAST:event_btnUpdateActionPerformed

    private void btnSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchActionPerformed
        // TODO add your handling code here:
        String SQL = "select * from myaddress where firstname = ? ";
        
        String fname = searchTxt.getText();
       
        try {
            Class.forName("com.mysql.jdbc.Driver");
        } catch (ClassNotFoundException ex) {
           JOptionPane.showMessageDialog(this,"Driver Not Found");
        }
        try {
            Connection conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/addressbook", "root", "7278");
            PreparedStatement st = conn.prepareStatement(SQL);
            st.setObject(1, fname);
            
            ResultSet rst = st.executeQuery();
            
            if (rst.next()) {
                fnameTxt.setText(rst.getString("firstname"));
                lnameTxt.setText(rst.getString("lastname"));
                addressTxt.setText(rst.getString("address"));
                contactTxt.setText(rst.getString("contact"));
                emailTxt.setText(rst.getString("email"));
            
            }else{
                 JOptionPane.showMessageDialog(this,"Contact Not Founde !");
            } 
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(this, ex.getMessage());
        }
    }//GEN-LAST:event_btnSearchActionPerformed

    private void btnViewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewActionPerformed
        // TODO add your handling code here:
        new ViewAddressBook().setVisible(true);
    }//GEN-LAST:event_btnViewActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AddressBookViewForm1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AddressBookViewForm1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AddressBookViewForm1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AddressBookViewForm1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AddressBookViewForm1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField addressTxt;
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnSearch;
    private javax.swing.JButton btnUpdate;
    private javax.swing.JButton btnView;
    private javax.swing.JTextField contactTxt;
    private javax.swing.JTextField emailTxt;
    private javax.swing.JTextField fnameTxt;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField lnameTxt;
    private javax.swing.JTextField searchTxt;
    // End of variables declaration//GEN-END:variables
}
